### ISSUE TITLE
Mini-Bug: CSS for a.wikilink1:link defines "white" as important...

### ISSUE THREAD

**Issue by dweia** [splitbrain/dokuwiki-plugin-translation#79]
The file lib/plugins/translation/style.css has the following section in it:
```css
.dokuwiki div.plugin_translation ul li a.wikilink1:link,
.dokuwiki div.plugin_translation ul li a.wikilink1:hover,
.dokuwiki div.plugin_translation ul li a.wikilink1:active,
.dokuwiki div.plugin_translation ul li a.wikilink1:visited {
    background-color: #000080;
    color: #fff !important;
    text-decoration:none;
    padding: 0 0.2em;
    margin: 0.1em 0.2em;
    border: none !important;
}
```
This means, in the standard dokuwiki template, the language-links are displayed white on light-grey and totally unreadable. So either you should define the background-color also as **!important**, or remove the !important from color, or (preferrably) remove the entire section, that works for me best...

Greetings,
Dweia

P.S. This might be the same as issue #15, since the original effect was that I simply didn't see the text (until I selected it and found it was only white on light)
